package app

var defaultThemeVarsData = map[string]string{
	"about-page-accent":                       "var(--primary)",
	"about-page-background":                   "var(--background)",
	"about-page-color":                        "var(--white)",
	"background":                              "#0b1021",
	"background-darker":                       "#05070e",
	"black":                                   "#000",
	"cloud-backup-background":                 "var(--config-settings-background)",
	"cloud-backup-color":                      "var(--config-settings-color)",
	"code-editor-background":                  "var(--white)",
	"code-editor-color":                       "var(--black)",
	"config-code-background":                  "var(--white)",
	"config-code-color":                       "var(--background)",
	"config-settings-background":              "var(--background-darker)",
	"config-settings-color":                   "var(--primary)",
	"context-menu-background":                 "var(--background)",
	"context-menu-color":                      "var(--primary)",
	"context-menu-secondary-color":            "var(--background-darker)",
	"curve-factor":                            "8px",
	"curve-factor-navbar":                     "10px",
	"description-tooltip-background":          "var(--background-darker)",
	"description-tooltip-color":               "var(--primary)",
	"dimming-factor":                          "0.85",
	"danger":                                  "#f80363",
	"error":                                   "#fca016",
	"footer-background":                       "var(--background-darker)",
	"footer-text-color":                       "#5e6474",
	"footer-text-color-link":                  "var(--primary)",
	"font-body":                               "'Roboto','Helvetica Neue',Arial,sans-serif",
	"font-headings":                           "'Segoe UI','Helvetica Neue',Arial,sans-serif",
	"heading-text-color":                      "var(--primary)",
	"highlight-background":                    "var(--primary)",
	"highlight-color":                         "var(--background)",
	"info":                                    "#04e4f4",
	"interactive-editor-background":           "var(--background)",
	"interactive-editor-background-darker":    "var(--background-darker)",
	"interactive-editor-color":                "var(--primary)",
	"item-background":                         "#607d8b33",
	"item-background-hover":                   "#607d8b4d",
	"item-group-background":                   "#0b1021cc",
	"item-group-heading-text-color":           "var(--item-group-background)",
	"item-group-heading-text-color-hover":     "var(--background)",
	"item-group-outer-background":             "var(--primary)",
	"item-group-padding":                      "0.25rem",
	"item-group-shadow":                       "1px 1px 2px rgba(0,0,0,.45)",
	"item-hover-shadow":                       "0 1px 3px rgba(92,172,202,.35),0 1px 2px rgba(92,172,202,.4)",
	"item-shadow":                             "1px 1px 2px rgba(0,0,0,.42)",
	"item-text-color":                         "var(--primary)",
	"item-text-color-hover":                   "var(--item-text-color)",
	"loading-screen-background":               "var(--background)",
	"loading-screen-color":                    "var(--primary)",
	"login-form-background":                   "var(--background)",
	"login-form-background-secondary":         "var(--background-darker)",
	"login-form-color":                        "var(--primary)",
	"medium-grey":                             "#5e6474",
	"minimal-view-background-color":           "var(--background)",
	"minimal-view-group-background":           "var(--background-darker)",
	"minimal-view-group-color":                "var(--primary)",
	"minimal-view-search-background":          "var(--background-darker)",
	"minimal-view-search-color":               "var(--primary)",
	"minimal-view-section-heading-background": "var(--background-darker)",
	"minimal-view-section-heading-color":      "var(--primary)",
	"minimal-view-settings-color":             "var(--primary)",
	"minimal-view-title-color":                "var(--primary)",
	"nav-link-background-color":               "#607d8b33",
	"nav-link-background-color-hover":         "#607d8b33",
	"nav-link-border-color":                   "transparent",
	"nav-link-border-color-hover":             "var(--primary)",
	"nav-link-shadow":                         "1px 1px 2px rgba(35,35,35,.85)",
	"nav-link-shadow-hover":                   "1px 1px 2px rgba(35,35,35,.85)",
	"nav-link-text-color":                     "var(--primary)",
	"nav-link-text-color-hover":               "var(--primary)",
	"neutral":                                 "#272f4d",
	"outline-color":                           "transparent",
	"primary":                                 "#5cabca",
	"progress-bar":                            "var(--primary)",
	"scroll-bar-background":                   "var(--background-darker)",
	"scroll-bar-color":                        "var(--primary)",
	"scroll-bar-width":                        "10px",
	"search-container-background":             "var(--background-darker)",
	"search-field-background":                 "var(--background)",
	"search-label-color":                      "var(--settings-text-color)",
	"section-max-height":                      "2400px",
	"settings-background":                     "var(--background)",
	"settings-text-color":                     "var(--primary)",
	"side-bar-background":                     "var(--background-darker)",
	"side-bar-background-lighter":             "var(--background)",
	"side-bar-color":                          "var(--primary)",
	"side-bar-item-background":                "var(--side-bar-background)",
	"side-bar-item-color":                     "var(--side-bar-color)",
	"status-check-tooltip-background":         "var(--background-darker)",
	"status-check-tooltip-color":              "var(--primary)",
	"success":                                 "#20e253",
	"toast-background":                        "var(--primary)",
	"toast-color":                             "var(--background)",
	"transparent-30":                          "#0000004d",
	"transparent-50":                          "#00000080",
	"transparent-70":                          "#000000b3",
	"transparent-white-10":                    "#ffffff0f",
	"transparent-white-30":                    "#ffffff4d",
	"transparent-white-50":                    "#ffffff80",
	"transparent-white-70":                    "#ffffffb3",
	"warning":                                 "#f6f000",
	"welcome-popup-background":                "var(--background-darker)",
	"welcome-popup-text-color":                "var(--primary)",
	"white":                                   "#fff",
	"widget-accent-color":                     "var(--background)",
	"widget-background-color":                 "var(--background-darker)",
	"widget-base-background":                  "transparent",
	"widget-text-color":                       "var(--primary)",
	"workspace-web-content-background":        "var(--background)",
}

var themeOverridesData = map[string]map[string]string{
	"callisto": {
		"primary":               "#00CCB4",
		"background":            "#141b33",
		"background-darker":     "#060913",
		"item-group-background": "#0b1021",
		"item-background":       "var(--background)",
		"item-background-hover": "var(--background-darker)",
		"item-hover-shadow":     "0 1px 3px #00ccb4b3, 0 1px 2px #00ccb4bf",
		"font-body":             "'Inconsolata','Georgia',sans-serif",
		"font-headings":         "'PTMono','Courier New',monospace",
	},
	"thebe": {
		"background":                  "#141b33",
		"background-darker":           "#060913",
		"item-group-background":       "#0b1021",
		"item-background":             "#141b33",
		"item-background-hover":       "var(--background-darker)",
		"item-hover-shadow":           "0 1px 3px #9660ecb3, 0 1px 2px #9660ecbf",
		"primary":                     "#b187f5",
		"item-group-outer-background": "linear-gradient(45deg,#9660ec 2%,#5f60ea 51%,#9660ec 100%)",
		"font-headings":               "'PTMono','Courier New',monospace",
	},
	"dracula": {
		"font-headings":                       "'Shrikhand',sans-serif",
		"primary":                             "#98ace9",
		"background":                          "#44475a",
		"background-darker":                   "#282a36",
		"item-group-background":               "var(--background-darker)",
		"item-background":                     "var(--background-darker)",
		"item-background-hover":               "#191b22",
		"item-shadow":                         "1px 1px 3px #000000e6",
		"item-hover-shadow":                   "none",
		"settings-text-color":                 "var(--primary)",
		"config-settings-color":               "var(--primary)",
		"nav-link-background-color":           "var(--background)",
		"item-group-outer-background":         "var(--background-darker)",
		"login-form-background":               "var(--background-darker)",
		"item-group-heading-text-color":       "#8be9fd",
		"item-group-heading-text-color-hover": "#8be9fd",
	},
	"bee": {
		"primary":                   "#c3eb5c",
		"background":                "#0b1021",
		"item-background":           "#1c2636",
		"item-group-background":     "var(--background)",
		"nav-link-background-color": "var(--background)",
		"font-headings":             "'Sniglet',cursive",
	},
	"tiger": {
		"primary":                   "#f58233",
		"background":                "#0b1021",
		"item-background":           "#1c2636",
		"item-group-background":     "var(--background)",
		"nav-link-background-color": "var(--background)",
		"font-headings":             "'Sniglet',cursive",
	},
	"nord": {
		"primary":               "#D8DEE9",
		"background":            "#3B4252",
		"background-darker":     "#2E3440",
		"item-background":       "#434C5E",
		"item-background-hover": "#4C566A",
		"item-group-background": "#2E3440",
	},
	"minimal-dark": {
		"primary":                     "#d9e2f2",
		"background":                  "#0d1117",
		"background-darker":           "#090c10",
		"item-background":             "#161b22",
		"item-background-hover":       "#1d2430",
		"item-group-background":       "#0d1117",
		"nav-link-background-color":   "#161b22",
		"item-group-outer-background": "#202938",
		"heading-text-color":          "#f0f6fc",
	},
	"material-dark": {
		"primary":                     "#d9e2f2",
		"background":                  "#0d1117",
		"background-darker":           "#090c10",
		"item-background":             "#161b22",
		"item-background-hover":       "#1d2430",
		"item-group-background":       "#0d1117",
		"nav-link-background-color":   "#161b22",
		"item-group-outer-background": "#202938",
		"heading-text-color":          "#f0f6fc",
	},
	"colorful": {
		"primary":                     "#ffb347",
		"background":                  "#0c1222",
		"background-darker":           "#050915",
		"item-background":             "#18233a",
		"item-background-hover":       "#213050",
		"item-group-background":       "#0c1222",
		"item-group-outer-background": "linear-gradient(120deg,#ff7e5f,#feb47b)",
		"nav-link-background-color":   "#18233a",
		"heading-text-color":          "#ffd7a0",
	},
}
